import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '../app/components/header/header'
import 'bootstrap/dist/css/bootstrap.css'
import Footer from '../app/components/footer'
import { Roboto } from 'next/font/google'



const roboto = Roboto(
  {
    subsets: ['latin'],
    weight: '500'

  }
)

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
